### ISSUE TITLE
Visibility of New Question CTA

### ISSUE THREAD

**Issue by liamgold** [Kentico/community-portal#11]
### Motivation

When navigating through the [Q&A](https://community.kentico.com/q-and-a) listing page, it might not be immediately obvious where the New Question button is:

![image](https://github.com/user-attachments/assets/a1fdd4fc-1213-4d82-b1cc-6ca4cc209e04)

### Proposed solution

I think we should change the CTA to have a similar style to the Search button:

![image](https://github.com/user-attachments/assets/f5e5ad74-c4a3-4362-aaaa-8e005ea1f86e)

This makes it far easier to see the CTA.

@seangwright also proposed changing the text from New Question to New Discussion.

**Comment by seangwright** [comment]
What do you think about this approach?

![image](https://github.com/user-attachments/assets/18ca02c9-d783-46e6-8163-fd0f0ff85563)

It moves the CTA above the search. First you make a decision "Ask question or search for an answer?".
If you choose search, you scroll past the CTA and don't need to see it. If you choose ask question it's clear what the next step is.

![image](https://github.com/user-attachments/assets/7eb1e070-4fa9-4886-a006-9c7ba6b42be4)

**Comment by liamgold** [comment]
Yeah that's looks great, I think that's far clearer for users.

Are you still thinking of changing the text to "New Discussion" too?
