### ISSUE TITLE
Better image when sharing to social media

### ISSUE THREAD

**Issue by Jazzman1976** [Kentico/community-portal#6]
When I share an URL of the portal, the used Kentico logo image is not so nice.

An image with higher resolution could be set as default when sharing URLs to social media. This would make the share looking better.

**Comment by seangwright** [comment]
Yes, I think the open graph/meta content needs some attention. I'll look to get something deployed soon.

**Comment by seangwright** [comment]
https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fcommunity.kentico.com%2F

The OG image should be correct now.
