### ISSUE TITLE
Add "Kentico User Group UK" to Community Groups

### ISSUE THREAD

**Issue by liamgold** [Kentico/community-portal#7]
### Motivation

We've launched a new User Group on LinkedIn today, [Kentico User Group UK](https://www.linkedin.com/groups/13057217/).

### Proposed solution

Add Kentico User Group UK to the Community Groups section of the community portal.

**Comment by seangwright** [comment]
Awesome!

I've added it to the [Community page](https://community.kentico.com/community). If you want the content/image updated, let me know.
